apiVersion: v1
kind: Service
metadata:
  name: dropify-backend
  namespace: dropify
spec:
  selector:
    app: dropify-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
