apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropify-app
  namespace: dropify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dropify-app
  template:
    metadata:
      labels:
        app: dropify-app
    spec:
      containers:
        - name: app
          image: milatodorovska/dropify-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
