apiVersion: v1
kind: Service
metadata:
  name: dropify-frontend
  namespace: dropify
spec:
  selector:
    app: dropify-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
