spring:
  datasource:
    url: jdbc:mysql://dropify-mysql:3306/dropify?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: dropify
    password: dropifypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # Automatically create/update tables based on entities
    show-sql: true       # Optional: show SQL statements in console
    properties:
      hibernate:
        format_sql: true
  application:
    name: dropify


eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix: DEBUG

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

servlet:
  multipart:
    enabled: true
    max-file-size: 2MB   # Maximum file size allowed per upload
    max-request-size: 2MB

upload:
  dir: yourimagestoragefolder